// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvmVBakVytRXWYqi8MF_H7YwOq4C6yRyQ',
    appId: '1:1082893235801:web:27a8ee6ccdb12cda6ce348',
    messagingSenderId: '1082893235801',
    projectId: 'flutter-test-9c5f7',
    authDomain: 'flutter-test-9c5f7.firebaseapp.com',
    storageBucket: 'flutter-test-9c5f7.firebasestorage.app',
    measurementId: 'G-PYEC1QP6LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmoV3Ph3rBQAGTOIgCUNm0cU-uYmTGzcw',
    appId: '1:1082893235801:android:0e4aaa05a98a08f46ce348',
    messagingSenderId: '1082893235801',
    projectId: 'flutter-test-9c5f7',
    storageBucket: 'flutter-test-9c5f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgP3EV3fXgCn1qiKzE6DjjkLhqcMgbjk',
    appId: '1:1082893235801:ios:373fe30e43c4e37e6ce348',
    messagingSenderId: '1082893235801',
    projectId: 'flutter-test-9c5f7',
    storageBucket: 'flutter-test-9c5f7.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase2ndtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhgP3EV3fXgCn1qiKzE6DjjkLhqcMgbjk',
    appId: '1:1082893235801:ios:373fe30e43c4e37e6ce348',
    messagingSenderId: '1082893235801',
    projectId: 'flutter-test-9c5f7',
    storageBucket: 'flutter-test-9c5f7.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase2ndtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvmVBakVytRXWYqi8MF_H7YwOq4C6yRyQ',
    appId: '1:1082893235801:web:219b67f7e42494fb6ce348',
    messagingSenderId: '1082893235801',
    projectId: 'flutter-test-9c5f7',
    authDomain: 'flutter-test-9c5f7.firebaseapp.com',
    storageBucket: 'flutter-test-9c5f7.firebasestorage.app',
    measurementId: 'G-1VL20CF6BQ',
  );
}
